apiVersion: v2
name: decisionrules-gke
description: DecisionRules application deployment for Google Kubernetes Engine (GKE)
version: 0.1.0
appVersion: "1.25.1"
type: application
icon: https://worthy-deer-b71b61c421.media.strapiapp.com/logo_dr_hexagon_9450d15423.png

annotations:
  artifacthub.io/name: decisionrules-gke
  artifacthub.io/description: "Deploy DecisionRules services (client, server, BI, AI) to Google Kubernetes Engine (GKE) with GKE Ingress."
  artifacthub.io/tags: "decisionrules,gcp,gke,google-cloud,client,server,bi,ai,rules,workflow"
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.decisionrules.io/
  artifacthub.io/providers: |
    - name: DecisionRules
      url: https://decisionrules.io/
  artifacthub.io/maintainers: |
    - name: DecisionRules Team
      email: support@decisionrules.io
  artifacthub.io/license: Apache-2.0
