apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: decisionrules-server-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: decisionrules-server
  type: LoadBalancer
