{{- if .Values.bi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: decisionrules-bi-service
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: decisionrules-bi
  type: LoadBalancer
{{- end -}}
