apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: decisionrules-client-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: decisionrules-client
  type: LoadBalancer
