{{- if .Values.ai.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: decisionrules-ai-service
  labels:
    run: decisionrules-ai
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - port: 80
    targetPort: 8084
  selector:
    run: decisionrules-ai
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
{{- end -}}
