apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: decisionrules-client-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: decisionrules-client
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
