apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: decisionrules-server-autoscaling
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decisionrules-server
  {{- $profile := include "decisionrules.solverProfile" . | fromYaml }}
  minReplicas: {{ .Values.autoscalingServer.minReplicas | default $profile.minReplicas }}
  maxReplicas: {{ .Values.autoscalingServer.maxReplicas | default $profile.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscalingServer.targetCPUUtilizationPercentage }}