{{- if .Values.bi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: decisionrules-bi-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: decisionrules-bi
  ports:
    - port: 8082
{{- end -}}
